name: Android CI


on:
  push:
    #branches: [ master ]
#  pull_request:
    #branches: [ master ]
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.0.0
      with:
        submodules: 'true'
    - uses: gradle/wrapper-validation-action@v1
      name: Check if Gradle wrapper is legit
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: setup android-ndk
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r21e
        add-to-path: true
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build Freedoom-Android
      run: |
          pushd doom/src/main/jni
          ndk-build
          popd
          cd doom
          ../gradlew assembleRelease


#    - uses: r0adkll/sign-android-release@v1
#      name: Sign app APK
#      # ID used to access action output
#      id: sign_app
#      with:
#        releaseDirectory: build/outputs/apk/release
#        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
#        alias: ${{ secrets.ALIAS }}
#        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}


    - name: Sign APK with debug key
      run: |
          cd ..
          wget https://github.com/patrickfav/uber-apk-signer/releases/download/v1.3.0/uber-apk-signer-1.3.0.jar
          java -jar uber-apk-signer-1.3.0.jar -a doom/build/outputs/apk/release --out doom/build/outputs/apk/release/signed
      
    - uses: actions/upload-artifact@v3
      name: upload APKs
      with:
        name: FreeDoom-android
        path: doom/build/outputs/apk/release/
